research_task:
  description: >
    Collect and preprocess research materials, including PDFs, based on {topic}
  expected_output: >
    A vector database with findingds from {topic}.
  tools:
    - PDFExtractionTool
  

reporting_task:
  description: >
    Generate a markdown report from research results.
  expected_output: >
    A detailed report based on the findings of research.
  output_file: >
    report.md
  tools:
    - MarkdownFormatter
    - SummaryTool
